module "apimanagement" {
  source = "./apimanagement"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  status_silenced                          = "${var.apimanagement_status_silenced}"
  status_message                           = "${var.apimanagement_status_message}"
  status_time_aggregator                   = "${var.apimanagement_status_time_aggregator}"
  status_timeframe                         = "${var.apimanagement_status_timeframe}"
  failed_requests_silenced                 = "${var.apimanagement_failed_requests_silenced}"
  failed_requests_message                  = "${var.apimanagement_failed_requests_message}"
  failed_requests_timeframe                = "${var.apimanagement_failed_requests_timeframe}"
  failed_requests_threshold_critical       = "${var.apimanagement_failed_requests_threshold_critical}"
  failed_requests_threshold_warning        = "${var.apimanagement_failed_requests_threshold_warning}"
  other_requests_silenced                  = "${var.apimanagement_other_requests_silenced}"
  other_requests_message                   = "${var.apimanagement_other_requests_message}"
  other_requests_timeframe                 = "${var.apimanagement_other_requests_timeframe}"
  other_requests_threshold_critical        = "${var.apimanagement_other_requests_threshold_critical}"
  other_requests_threshold_warning         = "${var.apimanagement_other_requests_threshold_warning}"
  successful_requests_silenced             = "${var.apimanagement_successful_requests_silenced}"
  successful_requests_message              = "${var.apimanagement_successful_requests_message}"
  successful_requests_timeframe            = "${var.apimanagement_successful_requests_timeframe}"
  successful_requests_threshold_critical   = "${var.apimanagement_successful_requests_threshold_critical}"
  successful_requests_threshold_warning    = "${var.apimanagement_successful_requests_threshold_warning}"
  unauthorized_requests_silenced           = "${var.apimanagement_unauthorized_requests_silenced}"
  unauthorized_requests_message            = "${var.apimanagement_unauthorized_requests_message}"
  unauthorized_requests_timeframe          = "${var.apimanagement_unauthorized_requests_timeframe}"
  unauthorized_requests_threshold_critical = "${var.apimanagement_unauthorized_requests_threshold_critical}"
  unauthorized_requests_threshold_warning  = "${var.apimanagement_unauthorized_requests_threshold_warning}"
}

module "appservices" {
  source = "./app-services"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  http_successful_requests_silenced           = "${var.appservices_http_successful_requests_silenced}"
  http_successful_requests_message            = "${var.appservices_http_successful_requests_message}"
  http_successful_requests_timeframe          = "${var.appservices_http_successful_requests_timeframe}"
  http_successful_requests_threshold_critical = "${var.appservices_http_successful_requests_threshold_critical}"
  http_successful_requests_threshold_warning  = "${var.appservices_http_successful_requests_threshold_warning}"
  http_5xx_requests_silenced                  = "${var.appservices_http_5xx_requests_silenced}"
  http_5xx_requests_message                   = "${var.appservices_http_5xx_requests_message}"
  http_5xx_requests_timeframe                 = "${var.appservices_http_5xx_requests_timeframe}"
  http_5xx_requests_threshold_critical        = "${var.appservices_http_5xx_requests_threshold_critical}"
  http_5xx_requests_threshold_warning         = "${var.appservices_http_5xx_requests_threshold_warning}"
  http_4xx_requests_silenced                  = "${var.appservices_http_4xx_requests_silenced}"
  http_4xx_requests_message                   = "${var.appservices_http_4xx_requests_message}"
  http_4xx_requests_timeframe                 = "${var.appservices_http_4xx_requests_timeframe}"
  http_4xx_requests_threshold_critical        = "${var.appservices_http_4xx_requests_threshold_critical}"
  http_4xx_requests_threshold_warning         = "${var.appservices_http_4xx_requests_threshold_warning}"
  memory_usage_silenced                       = "${var.appservices_memory_usage_silenced}"
  memory_usage_message                        = "${var.appservices_memory_usage_message}"
  memory_usage_time_aggregator                = "${var.appservices_memory_usage_time_aggregator}"
  memory_usage_timeframe                      = "${var.appservices_memory_usage_timeframe}"
  memory_usage_threshold_critical             = "${var.appservices_memory_usage_threshold_critical}"
  memory_usage_threshold_warning              = "${var.appservices_memory_usage_threshold_warning}"
  response_time_silenced                      = "${var.appservices_response_time_silenced}"
  response_time_message                       = "${var.appservices_response_time_message}"
  response_time_time_aggregator               = "${var.appservices_response_time_time_aggregator}"
  response_time_timeframe                     = "${var.appservices_response_time_timeframe}"
  response_time_threshold_critical            = "${var.appservices_response_time_threshold_critical}"
  response_time_threshold_warning             = "${var.appservices_response_time_threshold_warning}"
}

module "eventhub" {
  source = "./eventhub"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  status_silenced                        = "${var.eventhub_status_silenced}"
  status_message                         = "${var.eventhub_status_message}"
  status_time_aggregator                 = "${var.eventhub_status_time_aggregator}"
  status_timeframe                       = "${var.eventhub_status_timeframe}"
  errors_rate_silenced                   = "${var.eventhub_errors_rate_silenced}"
  errors_rate_message                    = "${var.eventhub_errors_rate_message}"
  errors_rate_timeframe                  = "${var.eventhub_errors_rate_timeframe}"
  errors_rate_thresold_critical          = "${var.eventhub_errors_rate_thresold_critical}"
  errors_rate_thresold_warning           = "${var.eventhub_errors_rate_thresold_warning}"
  failed_requests_rate_silenced          = "${var.eventhub_failed_requests_rate_silenced}"
  failed_requests_rate_message           = "${var.eventhub_failed_requests_rate_message}"
  failed_requests_rate_timeframe         = "${var.eventhub_failed_requests_rate_timeframe}"
  failed_requests_rate_thresold_critical = "${var.eventhub_failed_requests_rate_thresold_critical}"
  failed_requests_rate_thresold_warning  = "${var.eventhub_failed_requests_rate_thresold_warning}"
}

module "iothub" {
  source = "./iothubs"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags = "${var.non_taggable_filter_tags}"

  status_silenced                                       = "${var.iothub_status_silenced}"
  status_message                                        = "${var.iothub_status_message}"
  status_time_aggregator                                = "${var.iothub_status_time_aggregator}"
  status_timeframe                                      = "${var.iothub_status_timeframe}"
  total_devices_silenced                                = "${var.iothub_total_devices_silenced}"
  total_devices_message                                 = "${var.iothub_total_devices_message}"
  total_devices_time_aggregator                         = "${var.iothub_total_devices_time_aggregator}"
  total_devices_timeframe                               = "${var.iothub_total_devices_timeframe}"
  too_many_d2c_telemetry_ingress_nosent_silenced        = "${var.iothub_too_many_d2c_telemetry_ingress_nosent_silenced}"
  too_many_d2c_telemetry_ingress_nosent_message         = "${var.iothub_too_many_d2c_telemetry_ingress_nosent_message}"
  too_many_d2c_telemetry_ingress_nosent_timeframe       = "${var.iothub_too_many_d2c_telemetry_ingress_nosent_timeframe}"
  dropped_d2c_telemetry_egress_silenced                 = "${var.iothub_dropped_d2c_telemetry_egress_silenced}"
  dropped_d2c_telemetry_egress_message                  = "${var.iothub_dropped_d2c_telemetry_egress_message}"
  dropped_d2c_telemetry_egress_timeframe                = "${var.iothub_dropped_d2c_telemetry_egress_timeframe}"
  dropped_d2c_telemetry_egress_rate_threshold_critical  = "${var.iothub_dropped_d2c_telemetry_egress_rate_threshold_critical}"
  dropped_d2c_telemetry_egress_rate_threshold_warning   = "${var.iothub_dropped_d2c_telemetry_egress_rate_threshold_warning}"
  failed_c2d_methods_rate_silenced                      = "${var.iothub_failed_c2d_methods_rate_silenced}"
  failed_c2d_methods_rate_message                       = "${var.iothub_failed_c2d_methods_rate_message}"
  failed_c2d_methods_rate_timeframe                     = "${var.iothub_failed_c2d_methods_rate_timeframe}"
  failed_c2d_methods_rate_threshold_critical            = "${var.iothub_failed_c2d_methods_rate_threshold_critical}"
  failed_c2d_methods_rate_threshold_warning             = "${var.iothub_failed_c2d_methods_rate_threshold_warning}"
  failed_c2d_twin_read_rate_silenced                    = "${var.iothub_failed_c2d_twin_read_rate_silenced}"
  failed_c2d_twin_read_rate_message                     = "${var.iothub_failed_c2d_twin_read_rate_message}"
  failed_c2d_twin_read_rate_timeframe                   = "${var.iothub_failed_c2d_twin_read_rate_timeframe}"
  failed_c2d_twin_read_rate_threshold_critical          = "${var.iothub_failed_c2d_twin_read_rate_threshold_critical}"
  failed_c2d_twin_read_rate_threshold_warning           = "${var.iothub_failed_c2d_twin_read_rate_threshold_warning}"
  failed_c2d_twin_update_rate_silenced                  = "${var.iothub_failed_c2d_twin_update_rate_silenced}"
  failed_c2d_twin_update_rate_message                   = "${var.iothub_failed_c2d_twin_update_rate_message}"
  failed_c2d_twin_update_rate_timeframe                 = "${var.iothub_failed_c2d_twin_update_rate_timeframe}"
  failed_c2d_twin_update_rate_threshold_critical        = "${var.iothub_failed_c2d_twin_update_rate_threshold_critical}"
  failed_c2d_twin_update_rate_threshold_warning         = "${var.iothub_failed_c2d_twin_update_rate_threshold_warning}"
  failed_d2c_twin_read_rate_silenced                    = "${var.iothub_failed_d2c_twin_read_rate_silenced}"
  failed_d2c_twin_read_rate_message                     = "${var.iothub_failed_d2c_twin_read_rate_message}"
  failed_d2c_twin_read_rate_timeframe                   = "${var.iothub_failed_d2c_twin_read_rate_timeframe}"
  failed_d2c_twin_read_rate_threshold_critical          = "${var.iothub_failed_d2c_twin_read_rate_threshold_critical}"
  failed_d2c_twin_read_rate_threshold_warning           = "${var.iothub_failed_d2c_twin_read_rate_threshold_warning}"
  failed_d2c_twin_update_rate_silenced                  = "${var.iothub_failed_d2c_twin_update_rate_silenced}"
  failed_d2c_twin_update_rate_message                   = "${var.iothub_failed_d2c_twin_update_rate_message}"
  failed_d2c_twin_update_rate_timeframe                 = "${var.iothub_failed_d2c_twin_update_rate_timeframe}"
  failed_d2c_twin_update_rate_threshold_critical        = "${var.iothub_failed_d2c_twin_update_rate_threshold_critical}"
  failed_d2c_twin_update_rate_threshold_warning         = "${var.iothub_failed_d2c_twin_update_rate_threshold_warning}"
  failed_jobs_rate_silenced                             = "${var.iothub_failed_jobs_rate_silenced}"
  failed_jobs_rate_message                              = "${var.iothub_failed_jobs_rate_message}"
  failed_jobs_rate_timeframe                            = "${var.iothub_failed_jobs_rate_timeframe}"
  failed_jobs_rate_threshold_critical                   = "${var.iothub_failed_jobs_rate_threshold_critical}"
  failed_jobs_rate_threshold_warning                    = "${var.iothub_failed_jobs_rate_threshold_warning}"
  failed_listjobs_rate_silenced                         = "${var.iothub_failed_listjobs_rate_silenced}"
  failed_listjobs_rate_message                          = "${var.iothub_failed_listjobs_rate_message}"
  failed_listjobs_rate_timeframe                        = "${var.iothub_failed_listjobs_rate_timeframe}"
  failed_listjobs_rate_threshold_critical               = "${var.iothub_failed_listjobs_rate_threshold_critical}"
  failed_listjobs_rate_threshold_warning                = "${var.iothub_failed_listjobs_rate_threshold_warning}"
  failed_queryjobs_rate_silenced                        = "${var.iothub_failed_queryjobs_rate_silenced}"
  failed_queryjobs_rate_message                         = "${var.iothub_failed_queryjobs_rate_message}"
  failed_queryjobs_rate_timeframe                       = "${var.iothub_failed_queryjobs_rate_timeframe}"
  failed_queryjobs_rate_threshold_critical              = "${var.iothub_failed_queryjobs_rate_threshold_critical}"
  failed_queryjobs_rate_threshold_warning               = "${var.iothub_failed_queryjobs_rate_threshold_warning}"
  invalid_d2c_telemetry_egress_silenced                 = "${var.iothub_invalid_d2c_telemetry_egress_silenced}"
  invalid_d2c_telemetry_egress_message                  = "${var.iothub_invalid_d2c_telemetry_egress_message}"
  invalid_d2c_telemetry_egress_timeframe                = "${var.iothub_invalid_d2c_telemetry_egress_timeframe}"
  invalid_d2c_telemetry_egress_rate_threshold_critical  = "${var.iothub_invalid_d2c_telemetry_egress_rate_threshold_critical}"
  invalid_d2c_telemetry_egress_rate_threshold_warning   = "${var.iothub_invalid_d2c_telemetry_egress_rate_threshold_warning}"
  orphaned_d2c_telemetry_egress_silenced                = "${var.iothub_orphaned_d2c_telemetry_egress_silenced}"
  orphaned_d2c_telemetry_egress_message                 = "${var.iothub_orphaned_d2c_telemetry_egress_message}"
  orphaned_d2c_telemetry_egress_timeframe               = "${var.iothub_orphaned_d2c_telemetry_egress_timeframe}"
  orphaned_d2c_telemetry_egress_rate_threshold_critical = "${var.iothub_orphaned_d2c_telemetry_egress_rate_threshold_critical}"
  orphaned_d2c_telemetry_egress_rate_threshold_warning  = "${var.iothub_orphaned_d2c_telemetry_egress_rate_threshold_warning}"
}

module "redis" {
  source = "./redis"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  status_silenced                           = "${var.redis_status_silenced}"
  status_message                            = "${var.redis_status_message}"
  status_time_aggregator                    = "${var.redis_status_time_aggregator}"
  status_timeframe                          = "${var.redis_status_timeframe}"
  evictedkeys_limit_silenced                = "${var.redis_evictedkeys_limit_silenced}"
  evictedkeys_limit_message                 = "${var.redis_evictedkeys_limit_message}"
  evictedkeys_limit_time_aggregator         = "${var.redis_evictedkeys_limit_time_aggregator}"
  evictedkeys_limit_timeframe               = "${var.redis_evictedkeys_limit_timeframe}"
  evictedkeys_limit_threshold_critical      = "${var.redis_evictedkeys_limit_threshold_critical}"
  evictedkeys_limit_threshold_warning       = "${var.redis_evictedkeys_limit_threshold_warning}"
  percent_processor_time_silenced           = "${var.redis_percent_processor_time_silenced}"
  percent_processor_time_message            = "${var.redis_percent_processor_time_message}"
  percent_processor_time_time_aggregator    = "${var.redis_percent_processor_time_time_aggregator}"
  percent_processor_time_timeframe          = "${var.redis_percent_processor_time_timeframe}"
  percent_processor_time_threshold_critical = "${var.redis_percent_processor_time_threshold_critical}"
  percent_processor_time_threshold_warning  = "${var.redis_percent_processor_time_threshold_warning}"
  server_load_rate_silenced                 = "${var.redis_server_load_rate_silenced}"
  server_load_rate_message                  = "${var.redis_server_load_rate_message}"
  server_load_rate_time_aggregator          = "${var.redis_server_load_rate_time_aggregator}"
  server_load_rate_timeframe                = "${var.redis_server_load_rate_timeframe}"
  server_load_rate_threshold_critical       = "${var.redis_server_load_rate_threshold_critical}"
  server_load_rate_threshold_warning        = "${var.redis_server_load_rate_threshold_warning}"
}

module "servicebus" {
  source = "./servicebus"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  status_silenced        = "${var.servicebus_status_silenced}"
  status_message         = "${var.servicebus_status_message}"
  status_timeframe       = "${var.servicebus_status_timeframe}"
  status_time_aggregator = "${var.servicebus_status_time_aggregator}"

  no_active_connections_silenced        = "${var.servicebus_no_active_connections_silenced}"
  no_active_connections_message         = "${var.servicebus_no_active_connections_message}"
  no_active_connections_timeframe       = "${var.servicebus_no_active_connections_timeframe}"
  no_active_connections_time_aggregator = "${var.servicebus_no_active_connections_time_aggregator}"

  server_errors_silenced           = "${var.servicebus_server_errors_silenced}"
  server_errors_message            = "${var.servicebus_server_errors_message}"
  server_errors_timeframe          = "${var.servicebus_server_errors_timeframe}"
  server_errors_threshold_critical = "${var.servicebus_server_errors_threshold_critical}"
  server_errors_threshold_warning  = "${var.servicebus_server_errors_threshold_warning}"

  user_errors_silenced           = "${var.servicebus_user_errors_silenced}"
  user_errors_message            = "${var.servicebus_user_errors_message}"
  user_errors_timeframe          = "${var.servicebus_user_errors_timeframe}"
  user_errors_threshold_critical = "${var.servicebus_user_errors_threshold_critical}"
  user_errors_threshold_warning  = "${var.servicebus_user_errors_threshold_warning}"
}

module "sqldatabase" {
  source = "./sql-database"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  cpu_silenced                 = "${var.sqldatabase_cpu_silenced}"
  cpu_message                  = "${var.sqldatabase_cpu_message}"
  cpu_time_aggregator          = "${var.sqldatabase_cpu_time_aggregator}"
  cpu_timeframe                = "${var.sqldatabase_cpu_timeframe}"
  cpu_threshold_critical       = "${var.sqldatabase_cpu_threshold_critical}"
  cpu_threshold_warning        = "${var.sqldatabase_cpu_threshold_warning}"
  deadlock_silenced            = "${var.sqldatabase_deadlock_silenced}"
  deadlock_message             = "${var.sqldatabase_deadlock_message}"
  deadlock_timeframe           = "${var.sqldatabase_deadlock_timeframe}"
  deadlock_threshold_critical  = "${var.sqldatabase_deadlock_threshold_critical}"
  diskspace_silenced           = "${var.sqldatabase_diskspace_silenced}"
  diskspace_message            = "${var.sqldatabase_diskspace_message}"
  diskspace_time_aggregator    = "${var.sqldatabase_diskspace_time_aggregator}"
  diskspace_timeframe          = "${var.sqldatabase_diskspace_timeframe}"
  diskspace_threshold_critical = "${var.sqldatabase_diskspace_threshold_critical}"
  diskspace_threshold_warning  = "${var.sqldatabase_diskspace_threshold_warning}"
  dtu_silenced                 = "${var.sqldatabase_dtu_silenced}"
  dtu_message                  = "${var.sqldatabase_dtu_message}"
  dtu_time_aggregator          = "${var.sqldatabase_dtu_time_aggregator}"
  dtu_timeframe                = "${var.sqldatabase_dtu_timeframe}"
  dtu_threshold_critical       = "${var.sqldatabase_dtu_threshold_critical}"
  dtu_threshold_warning        = "${var.sqldatabase_dtu_threshold_warning}"
}

module "storage" {
  source = "./storage"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  authorization_error_requests_silenced           = "${var.storage_authorization_error_requests_silenced}"
  authorization_error_requests_message            = "${var.storage_authorization_error_requests_message}"
  authorization_error_requests_time_aggregator    = "${var.storage_authorization_error_requests_time_aggregator}"
  authorization_error_requests_timeframe          = "${var.storage_authorization_error_requests_timeframe}"
  authorization_error_requests_threshold_critical = "${var.storage_authorization_error_requests_threshold_critical}"
  authorization_error_requests_threshold_warning  = "${var.storage_authorization_error_requests_threshold_warning}"
  availability_silenced                           = "${var.storage_availability_silenced}"
  availability_message                            = "${var.storage_availability_message}"
  availability_time_aggregator                    = "${var.storage_availability_time_aggregator}"
  availability_timeframe                          = "${var.storage_availability_timeframe}"
  availability_threshold_critical                 = "${var.storage_availability_threshold_critical}"
  availability_threshold_warning                  = "${var.storage_availability_threshold_warning}"
  client_other_error_requests_silenced            = "${var.storage_client_other_error_requests_silenced}"
  client_other_error_requests_message             = "${var.storage_client_other_error_requests_message}"
  client_other_error_requests_time_aggregator     = "${var.storage_client_other_error_requests_time_aggregator}"
  client_other_error_requests_timeframe           = "${var.storage_client_other_error_requests_timeframe}"
  client_other_error_requests_threshold_critical  = "${var.storage_client_other_error_requests_threshold_critical}"
  client_other_error_requests_threshold_warning   = "${var.storage_client_other_error_requests_threshold_warning}"
  latency_silenced                                = "${var.storage_latency_silenced}"
  latency_message                                 = "${var.storage_latency_message}"
  latency_time_aggregator                         = "${var.storage_latency_time_aggregator}"
  latency_timeframe                               = "${var.storage_latency_timeframe}"
  latency_threshold_critical                      = "${var.storage_latency_threshold_critical}"
  latency_threshold_warning                       = "${var.storage_latency_threshold_warning}"
  network_error_requests_silenced                 = "${var.storage_network_error_requests_silenced}"
  network_error_requests_message                  = "${var.storage_network_error_requests_message}"
  network_error_requests_time_aggregator          = "${var.storage_network_error_requests_time_aggregator}"
  network_error_requests_timeframe                = "${var.storage_network_error_requests_timeframe}"
  network_error_requests_threshold_critical       = "${var.storage_network_error_requests_threshold_critical}"
  network_error_requests_threshold_warning        = "${var.storage_network_error_requests_threshold_warning}"
  server_other_error_requests_silenced            = "${var.storage_server_other_error_requests_silenced}"
  server_other_error_requests_message             = "${var.storage_server_other_error_requests_message}"
  server_other_error_requests_time_aggregator     = "${var.storage_server_other_error_requests_time_aggregator}"
  server_other_error_requests_timeframe           = "${var.storage_server_other_error_requests_timeframe}"
  server_other_error_requests_threshold_critical  = "${var.storage_server_other_error_requests_threshold_critical}"
  server_other_error_requests_threshold_warning   = "${var.storage_server_other_error_requests_threshold_warning}"
  successful_requests_silenced                    = "${var.storage_successful_requests_silenced}"
  successful_requests_message                     = "${var.storage_successful_requests_message}"
  successful_requests_time_aggregator             = "${var.storage_successful_requests_time_aggregator}"
  successful_requests_timeframe                   = "${var.storage_successful_requests_timeframe}"
  successful_requests_threshold_critical          = "${var.storage_successful_requests_threshold_critical}"
  successful_requests_threshold_warning           = "${var.storage_successful_requests_threshold_warning}"
  throttling_error_requests_silenced              = "${var.storage_throttling_error_requests_silenced}"
  throttling_error_requests_message               = "${var.storage_throttling_error_requests_message}"
  throttling_error_requests_time_aggregator       = "${var.storage_throttling_error_requests_time_aggregator}"
  throttling_error_requests_timeframe             = "${var.storage_throttling_error_requests_timeframe}"
  throttling_error_requests_threshold_critical    = "${var.storage_throttling_error_requests_threshold_critical}"
  throttling_error_requests_threshold_warning     = "${var.storage_throttling_error_requests_threshold_warning}"
  timeout_error_requests_silenced                 = "${var.storage_timeout_error_requests_silenced}"
  timeout_error_requests_message                  = "${var.storage_timeout_error_requests_message}"
  timeout_error_requests_time_aggregator          = "${var.storage_timeout_error_requests_time_aggregator}"
  timeout_error_requests_timeframe                = "${var.storage_timeout_error_requests_timeframe}"
  timeout_error_requests_threshold_critical       = "${var.storage_timeout_error_requests_threshold_critical}"
  timeout_error_requests_threshold_warning        = "${var.storage_timeout_error_requests_threshold_warning}"
}

module "streamanalytics" {
  source = "./stream-analytics"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  conversion_errors_silenced                  = "${var.streamanalytics_conversion_errors_silenced}"
  conversion_errors_message                   = "${var.streamanalytics_conversion_errors_message}"
  conversion_errors_time_aggregator           = "${var.streamanalytics_conversion_errors_time_aggregator}"
  conversion_errors_timeframe                 = "${var.streamanalytics_conversion_errors_timeframe}"
  conversion_errors_threshold_critical        = "${var.streamanalytics_conversion_errors_threshold_critical}"
  conversion_errors_threshold_warning         = "${var.streamanalytics_conversion_errors_threshold_warning}"
  failed_function_requests_silenced           = "${var.streamanalytics_failed_function_requests_silenced}"
  failed_function_requests_message            = "${var.streamanalytics_failed_function_requests_message}"
  failed_function_requests_timeframe          = "${var.streamanalytics_failed_function_requests_timeframe}"
  failed_function_requests_threshold_critical = "${var.streamanalytics_failed_function_requests_threshold_critical}"
  failed_function_requests_threshold_warning  = "${var.streamanalytics_failed_function_requests_threshold_warning}"
  runtime_errors_silenced                     = "${var.streamanalytics_runtime_errors_silenced}"
  runtime_errors_message                      = "${var.streamanalytics_runtime_errors_message}"
  runtime_errors_time_aggregator              = "${var.streamanalytics_runtime_errors_time_aggregator}"
  runtime_errors_timeframe                    = "${var.streamanalytics_runtime_errors_timeframe}"
  runtime_errors_threshold_critical           = "${var.streamanalytics_runtime_errors_threshold_critical}"
  runtime_errors_threshold_warning            = "${var.streamanalytics_runtime_errors_threshold_warning}"
  su_utilization_silenced                     = "${var.streamanalytics_su_utilization_silenced}"
  su_utilization_message                      = "${var.streamanalytics_su_utilization_message}"
  su_utilization_time_aggregator              = "${var.streamanalytics_su_utilization_time_aggregator}"
  su_utilization_timeframe                    = "${var.streamanalytics_su_utilization_timeframe}"
  su_utilization_threshold_critical           = "${var.streamanalytics_su_utilization_threshold_critical}"
  su_utilization_threshold_warning            = "${var.streamanalytics_su_utilization_threshold_warning}"
}

module "cosmosdb" {
  source = "./cosmosdb"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  status_message         = "${var.cosmos_db_status_message}"
  status_silenced        = "${var.cosmos_db_status_silenced}"
  status_extra_tags      = "${var.cosmos_db_status_extra_tags}"
  status_time_aggregator = "${var.cosmos_db_status_time_aggregator}"
  status_timeframe       = "${var.cosmos_db_status_timeframe}"

  cosmos_db_4xx_request_rate_threshold_critical = "${var.cosmos_db_4xx_request_rate_threshold_critical}"
  cosmos_db_4xx_request_rate_threshold_warning  = "${var.cosmos_db_4xx_request_rate_threshold_warning}"
  cosmos_db_4xx_requests_message                = "${var.cosmos_db_4xx_requests_message}"
  cosmos_db_4xx_requests_silenced               = "${var.cosmos_db_4xx_requests_silenced}"
  cosmos_db_4xx_request_extra_tags              = "${var.cosmos_db_4xx_request_extra_tags}"
  cosmos_db_4xx_request_time_aggregator         = "${var.cosmos_db_4xx_request_time_aggregator}"
  cosmos_db_4xx_request_timeframe               = "${var.cosmos_db_4xx_request_timeframe}"

  cosmos_db_5xx_request_rate_threshold_critical = "${var.cosmos_db_5xx_request_rate_threshold_critical}"
  cosmos_db_5xx_request_rate_threshold_warning  = "${var.cosmos_db_5xx_request_rate_threshold_warning}"
  cosmos_db_5xx_requests_message                = "${var.cosmos_db_5xx_requests_message}"
  cosmos_db_5xx_requests_silenced               = "${var.cosmos_db_5xx_requests_silenced}"
  cosmos_db_5xx_request_rate_extra_tags         = "${var.cosmos_db_5xx_request_rate_extra_tags}"
  cosmos_db_5xx_request_time_aggregator         = "${var.cosmos_db_5xx_request_time_aggregator}"
  cosmos_db_5xx_request_timeframe               = "${var.cosmos_db_5xx_request_timeframe}"

  cosmos_db_no_request_message         = "${var.cosmos_db_no_request_message}"
  cosmos_db_no_request_silenced        = "${var.cosmos_db_no_request_silenced}"
  cosmos_db_no_request_extra_tags      = "${var.cosmos_db_no_request_extra_tags}"
  cosmos_db_no_request_time_aggregator = "${var.cosmos_db_no_request_time_aggregator}"
  cosmos_db_no_request_timeframe       = "${var.cosmos_db_no_request_timeframe}"

  cosmos_db_ru_utilization_rate_threshold_critical = "${var.cosmos_db_ru_utilization_rate_threshold_critical}"
  cosmos_db_ru_utilization_rate_threshold_warning  = "${var.cosmos_db_ru_utilization_rate_threshold_warning}"
  cosmos_db_ru_utilization_message                 = "${var.cosmos_db_ru_utilization_message}"
  cosmos_db_ru_utilization_silenced                = "${var.cosmos_db_ru_utilization_silenced}"
  cosmos_db_ru_utilization_extra_tags              = "${var.cosmos_db_ru_utilization_extra_tags}"
  cosmos_db_ru_utilization_time_aggregator         = "${var.cosmos_db_ru_utilization_time_aggregator}"
  cosmos_db_ru_utilization_timeframe               = "${var.cosmos_db_ru_utilization_timeframe}"
  cosmos_db_ru_utilization_collections             = "${var.cosmos_db_ru_utilization_collections}"
}

module "datalakestore" {
  source = "./datalakestore"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  status_silenced        = "${var.datalakestore_status_silenced}"
  status_message         = "${var.datalakestore_status_message}"
  status_timeframe       = "${var.datalakestore_status_timeframe}"
  status_time_aggregator = "${var.datalakestore_status_time_aggregator}"
  status_extra_tags      = "${var.datalakestore_status_extra_tags}"
}

module "keyvault" {
  source = "./keyvault"

  environment      = "${var.environment}"
  message          = "${var.message}"
  evaluation_delay = "${var.evaluation_delay}"
  new_host_delay   = "${var.new_host_delay}"

  filter_tags_use_defaults = "${var.filter_tags_use_defaults}"
  filter_tags_custom       = "${var.filter_tags_custom}"

  status_silenced        = "${var.keyvault_status_silenced}"
  status_message         = "${var.keyvault_status_message}"
  status_timeframe       = "${var.keyvault_status_timeframe}"
  status_time_aggregator = "${var.keyvault_status_time_aggregator}"
  status_extra_tags      = "${var.keyvault_status_extra_tags}"

  api_result_enabled            = "${var.keyvault_api_result_enabled}"
  api_result_silenced           = "${var.keyvault_api_result_silenced}"
  api_result_message            = "${var.keyvault_api_result_message}"
  api_result_timeframe          = "${var.keyvault_api_result_timeframe}"
  api_result_time_aggregator    = "${var.keyvault_api_result_time_aggregator}"
  api_result_threshold_critical = "${var.keyvault_api_result_threshold_critical}"
  api_result_threshold_warning  = "${var.keyvault_api_result_threshold_warning}"
  api_result_extra_tags         = "${var.keyvault_api_result_extra_tags}"

  api_latency_silenced           = "${var.keyvault_api_latency_silenced}"
  api_latency_message            = "${var.keyvault_api_latency_message}"
  api_latency_timeframe          = "${var.keyvault_api_latency_timeframe}"
  api_latency_time_aggregator    = "${var.keyvault_api_latency_time_aggregator}"
  api_latency_threshold_critical = "${var.keyvault_api_latency_threshold_critical}"
  api_latency_threshold_warning  = "${var.keyvault_api_latency_threshold_warning}"
  api_latency_extra_tags         = "${var.keyvault_api_latency_extra_tags}"
}
