---
name: Monitors

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'push' }}

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: "claranet/terraform-ci:1.1.5"

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          submodules: recursive

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_version: 1.1.5
          terraform_wrapper: false

      - name: Run auto update
        run: ./scripts/auto_update.sh

      - name: Check git diff
        run: ./scripts/auto_update.sh

      - name: Run auto update
        run: ./scripts/auto_update.sh

      - name: Check for changes
        run: git diff --exit-code
